### ISSUE TITLE
Manual search not working or simply no results gives errors in log

### ISSUE THREAD

**Issue by The-Drake** [gborri/Sick-Beard#6]
Here is my error log:

2014-05-08 15:12:26 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: No NZB/Torrent providers found or enabled in the sickbeard config. Please check your settings.
AA
AAUnboundLocalError: local variable 'ListCurEp' referenced before assignment
AA    if not ListCurEp:
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/tvcache.py", line 391, in findNeededEpisodes
AA    neededEps = self.findNeededEpisodes(episode, manualSearch)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/tvcache.py", line 339, in searchCache
AA    results = self.cache.searchCache(episode, manualSearch)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/providers/generic.py", line 225, in findEpisode
AA    curFoundResults = curProvider.findEpisode(episode, manualSearch=manualSearch)
AA  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/search.py", line 358, in findEpisode
2014-05-08 15:12:26 ERROR    SEARCHQUEUE-MANUAL-SEARCH :: Error while searching TNTVillage, skipping: local variable 'ListCurEp' referenced before assignment
2014-05-08 15:12:25 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching TNTVillage for xxxxxxxxxxxxxxxx - 6x01 - xxxxxxxxxxxxxxxxxx

**Comment by gborri** [comment]
Should be fixed. Could you try again?
Sorry for the problem.

Giovanni

**Comment by ToRvaLDz** [comment]
I got a similar problem, manual search doesn't work and sometimes I have to restart sickbeard to make backlog search work.

About the manual search I found this on debug log:
`2014-05-09 22:26:14 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Page: 1 of 100
2014-05-09 22:26:14 WARNING  SEARCHQUEUE-MANUAL-SEARCH :: TNTVillage page requested with url http://forum.tntvillage.scambioetico.org/?act=allreleases&st=0&cat=29 returned status code is 502: Bad Gateway
2014-05-09 22:25:52 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Search string: http://forum.tntvillage.scambioetico.org/?act=allreleases&st=0&cat=29
2014-05-09 22:25:52 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Page: 0 of 100
2014-05-09 22:25:52 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching TNTVillage for Il Trono di Spade - 4x03 - La fuga
2014-05-09 22:25:52 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: formatting pattern: %SN - %Sx%0E - %EN -> Il Trono di Spade - 4x03 - La fuga
2014-05-09 22:25:52 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN`

I think there's something wrong with authentication on tntvillage.

p.s. the episode is available on tnt

**Comment by gborri** [comment]
From what i have seen in log you have paste, could be a network problem
(Bad Gateway) either from your point of view while could also be a tnt
problem. I think also that 100 page to download is a bit too high because
every hour sickbeard download 100 time the release page. I have set it to 4
because not always the pc is turned on but four page means 80 new torrent
in a day. 100 means 2000 new torrent release a day. The authentication i
think is fine. We need to keep attention not to overleoad tnt server
otherwise i will not work correctly for all of us.

Giovanni
Il 09/mag/2014 22:42 "ToRvaLDz" notifications@github.com ha scritto:

**Comment by The-Drake** [comment]
Actually the error is still there. And I find no new commit to test... :)

**Comment by gborri** [comment]
I have forgotten to push the commit on github. Sorry about that.
